[package]
name = "tun2socks5"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4", features = ["derive"] }
ctrlc2 = { version = "3.5", features = ["tokio", "termination"] }
dotenvy = "0.15"
env_logger = "0.10"
ipstack = { git = "https://github.com/ssrlive/ipstack.git" }
log = "0.4"
socks5-impl = { version = "0.5" }
thiserror = "1.0"
tokio = { version = "1.34", features = ["full"] }
trust-dns-proto = "0.23"
tun = { git = "https://github.com/ssrlive/rust-tun.git", features = ["async"] }
udp-stream = { version = "0.0.9", default-features = false }
url = "2.5"
